- filename: DBLP.bib
  search_type: FEED
  source_name: Journal of Management Information Systems
  source_url: ''
  search_parameters: 
    - endpoint: dblp
      params: SCOPE venue_key='journals/jmis' AND journal_abbreviated='J. Manag. Inf. Syst.'
  comment: ''
- filename: CROSSREF.bib
  search_type: FEED
  source_name: Journal of Management Information Systems
  source_url: ''
  search_parameters: 
    - endpoint: crossref
      params: SCOPE journal_issn='0742-1222'